---
- name: Deploy Frontend
  hosts: frontend
  tasks:
    - name: Pull frontend code from GitHub
      git:
        repo: 'https://github.com/koladetyk/FullStackLibraryDAPP.git'
        dest: /var/www/frontend
        version: frontend

    - name: Run Docker Container for Frontend
      docker_container:
        name: frontend
        image: 0mchevli/library-dapp-frontend:latest
        state: started
        ports:
          - "3000:3000"

- name: Deploy Blockchain (Ganache)
  hosts: blockchain
  tasks:
    - name: Pull blockchain code from GitHub
      git:
        repo: 'https://github.com/koladetyk/FullStackLibraryDAPP.git'
        dest: /var/www/blockchain
        version: blockchain

    - name: Run Docker Container for Ganache
      docker_container:
        name: ganache
        image: trufflesuite/ganache:latest
        state: started
        ports:
          - "8545:8545"
